In [1]:
import numpy as np
a = np.array([10, 20, 40, 60])
a

array([10, 20, 40, 60])

In [2]:
a1 = np.array([23, 45, 67, 87])
a1

array([23, 45, 67, 87])

## Data types and attribute

In [3]:
x = np.array([10, 20, 30, 40])
x

array([10, 20, 30, 40])

In [5]:
x1 = np.array([[1, 2, 3, 4, 5, 7],
               [4, 5, 6, 7, 5 ,6]])
x1

array([[1, 2, 3, 4, 5, 7],
       [4, 5, 6, 7, 5, 6]])

In [6]:
x1.dtype

dtype('int32')

In [7]:
x.dtype

dtype('int32')

In [18]:
x2 = np.array([[[12, 45, 67],
                [12, 34, 56],
                [45, 67, 89]],
               
              [[12, 34, 56,],
              [14, 23, 45],
              [20, 30, 40]]])
x2

array([[[12, 45, 67],
        [12, 34, 56],
        [45, 67, 89]],

       [[12, 34, 56],
        [14, 23, 45],
        [20, 30, 40]]])

In [17]:
x2.dtype


dtype('int32')

In [12]:
x2.shape

(1, 3, 3)

In [19]:
x. shape, x1.shape, x2.shape

((4,), (2, 6), (2, 3, 3))

In [25]:
x2.shape

(2, 3, 3)

In [27]:
type(x), type(x1), type(x2)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [28]:
x.size, x1.size, x2.size

(4, 12, 18)

In [29]:
x.ndim, x1.ndim, x2.ndim

(1, 2, 3)

# Create a DataFrame from numpy array

In [33]:
import pandas as pd
df = pd.DataFrame(x1)
df

0  1  2  3  4  5
0  1  2  3  4  5  7
1  4  5  6  7  5  6

# 2. Creating array

In [34]:
sample_array = np.array([12, 45, 65, 45, 67, 87])
sample_array

array([12, 45, 65, 45, 67, 87])

In [35]:
sample_array.dtype

dtype('int32')

In [36]:
sample_array.shape

(6,)

In [37]:
sample_array.size

6

In [57]:
import random
sample_random = np.random.rand(3, 5)  #Doesn't allow size argument, return float value
sample_random

array([[0.79360103, 0.84357877, 0.16644573, 0.0460731 , 0.46186176],
       [0.86402598, 0.15645737, 0.97365232, 0.96534945, 0.58983511],
       [0.78755264, 0.37268728, 0.15724398, 0.25464468, 0.4455157 ]])

In [48]:
ones = np.ones((2, 3))  #Doesn't allow size argument
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
Zeroes = np.zeros((3, 5))   #Doesn't allow size argument
Zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
sample_array2 = np.arange(2, 10, 3)  #Doesn't allow size argument
sample_array2

array([2, 5, 8])

In [55]:
sample_array3 = np.random.randint(10, 20, size=(3, 3))
sample_array3

array([[19, 13, 19],
       [13, 17, 14],
       [13, 12, 14]])

In [62]:
sample_array.dtype

dtype('int32')

In [64]:
sample_array2.dtype


dtype('int32')

In [67]:
sample_array4 = np.random.random((5, 6))  #return values from 0 to 1 range
sample_array4

array([[0.93904818, 0.27793359, 0.99782768, 0.70612791, 0.70979764,
        0.29015397],
       [0.20961802, 0.04884686, 0.63618312, 0.414847  , 0.3438545 ,
        0.05705409],
       [0.66981459, 0.69727775, 0.86553915, 0.26370453, 0.33419437,
        0.95315413],
       [0.44542257, 0.79345945, 0.01576483, 0.3504829 , 0.09612852,
        0.46027904],
       [0.64119908, 0.92679547, 0.63639696, 0.04219842, 0.16320083,
        0.48934142]])

# Pseudo random numbers

In [72]:
#creating a random array that will never change
np.random.seed(seed=0)
sample_random = np.random.randint(10, size=(10, 10))
sample_random
sample_random.dtype, sample_random.size, sample_random.shape

(dtype('int32'), 100, (10, 10))

In [71]:
data = pd.DataFrame(sample_random)
data

0  1  2  3  4  5  6  7  8  9
0  5  0  3  3  7  9  3  5  2  4
1  7  6  8  8  1  6  7  7  8  1
2  5  9  8  9  4  3  0  3  5  0
3  2  3  8  1  3  3  3  7  0  1
4  9  9  0  4  7  3  2  7  2  0
5  0  4  5  5  6  8  4  1  4  9
6  8  1  1  7  9  9  3  6  7  2
7  0  3  5  9  4  4  6  4  4  3
8  4  4  8  4  3  7  5  5  0  1
9  5  9  3  0  5  0  1  2  4  2

In [5]:
import numpy as np
import random
random_array = np.random.rand(2, 10, 3)    #two dimension and 10 rows and 3 columns 
random_array

array([[[0.91952118, 0.9822258 , 0.73485448],
        [0.64206106, 0.2735344 , 0.60398806],
        [0.6388307 , 0.60176751, 0.02263567],
        [0.58759762, 0.18816802, 0.50187884],
        [0.02100252, 0.25425724, 0.8399002 ],
        [0.30066692, 0.82268106, 0.23996523],
        [0.33798122, 0.94650954, 0.32909295],
        [0.99890605, 0.05528672, 0.65433057],
        [0.05171434, 0.83903185, 0.11344149],
        [0.26323319, 0.49129719, 0.80376562]],

       [[0.9238181 , 0.69105864, 0.10672315],
        [0.70871308, 0.27908292, 0.74427788],
        [0.35727799, 0.45632159, 0.06630289],
        [0.98792486, 0.08401449, 0.75242825],
        [0.51899141, 0.19746451, 0.52471902],
        [0.87691253, 0.3621108 , 0.50739948],
        [0.41868297, 0.60269259, 0.24785608],
        [0.59371373, 0.32611932, 0.90506873],
        [0.52818367, 0.09111889, 0.9878098 ],
        [0.91810941, 0.12328027, 0.84654581]]])

In [16]:
np.random.seed(2)
random_array1 = np.random.randint(2, 100, size=(5, 5))
random_array1

array([[42, 17, 74, 24, 45],
       [84, 77,  9, 36, 51],
       [97, 77, 87, 49, 65],
       [33, 92, 22, 39, 41],
       [69,  6, 44, 53, 40]])

In [14]:
random_array1

array([[42, 17, 74, 24, 45],
       [84, 77,  9, 36, 51],
       [97, 77, 87, 49, 65],
       [33, 92, 22, 39, 41],
       [69,  6, 44, 53, 40]])

In [3]:
import numpy as np
b= np.arange(25).reshape(5, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [5]:
c = np.arange(20)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
c[:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Dot product vs Element

In [40]:
import numpy as np
import random
np.random.seed(10)
a = np.random.randint(15, size=(3, 5))
b = np.random.randint(100, size=(10, 10))
a

array([[ 9, 13,  4,  0,  1],
       [11, 12,  9, 13,  0],
       [13,  1, 10,  8,  9]])

In [7]:
b

array([[ 3, 29, 16, 84, 82, 14, 51, 79, 17, 50],
       [53, 25, 48, 17, 32, 81, 80, 41, 90, 12],
       [30, 81, 17, 16,  0, 31, 73, 64, 38, 22],
       [96, 66, 67, 62, 95, 99, 27, 82, 62, 77],
       [48, 93, 75, 86, 37, 11, 21, 33, 95, 43],
       [88, 96, 73, 40, 43, 90, 71,  8, 85, 72],
       [28, 30, 89, 25, 78, 81, 85, 62, 13, 41],
       [33,  4, 87, 94, 28, 39, 91,  9,  7, 22],
       [32,  3,  9, 52, 76, 68, 30, 70, 74, 30],
       [ 9,  2, 65, 13, 75, 52,  5, 93, 84, 48]])

In [3]:
a.shape

(10, 10)

In [4]:
b.shape

(10, 10)

In [5]:
np.sum(a)
np.sum(b)

5186

In [9]:
a.size

100

In [10]:
np.sum(a)

4824

In [12]:
np.sum(b)

5053

In [13]:
np.sum(a, axis=1)

array([408, 490, 529, 395, 519, 428, 541, 512, 530, 472])

In [14]:
np.std(a)

30.363504409076363

In [26]:
np.var(a)

921.9423999999998

In [27]:
c = np.random.random(size=(3, 5))   #return a value between 0 and 1 and the value is fixed

In [21]:
c

array([[0.69389007, 0.10461974, 0.43960524, 0.16620215, 0.50697863],
       [0.81903586, 0.09010673, 0.80006875, 0.56512635, 0.58934771],
       [0.19810066, 0.43611826, 0.29590376, 0.03755768, 0.03068484]])

In [23]:
c.size

15

In [24]:
c.reshape(5, 3)

array([[0.69389007, 0.10461974, 0.43960524],
       [0.16620215, 0.50697863, 0.81903586],
       [0.09010673, 0.80006875, 0.56512635],
       [0.58934771, 0.19810066, 0.43611826],
       [0.29590376, 0.03755768, 0.03068484]])

In [25]:
c.T

array([[0.69389007, 0.81903586, 0.19810066],
       [0.10461974, 0.09010673, 0.43611826],
       [0.43960524, 0.80006875, 0.29590376],
       [0.16620215, 0.56512635, 0.03755768],
       [0.50697863, 0.58934771, 0.03068484]])

In [28]:
c.size

15

In [29]:
c.shape

(3, 5)

In [30]:
a.size

100

In [41]:
d = a.reshape(3, 5)
d

array([[ 9, 13,  4,  0,  1],
       [11, 12,  9, 13,  0],
       [13,  1, 10,  8,  9]])

In [42]:
c.size, d.size

(15, 15)

In [43]:
c.shape, d.shape

((3, 5), (3, 5))

In [44]:
c * d  3 #Element wise multiplacation

array([[ 4.077945  ,  9.683233  ,  2.22918162,  0.        ,  0.1680728 ],
       [ 9.22087453,  7.18862157,  7.04443336, 11.03061936,  0.        ],
       [10.15378802,  0.61573688,  0.21165191,  6.00371688,  1.5843792 ]])

In [47]:
# Dot product of matrics 
c.shape, d.shape  #first matrics columns and second matrics row must be same 


((3, 5), (3, 5))

In [50]:
d1 = d.reshape(5, 3)

In [53]:
d1

array([[ 9, 13,  4],
       [ 0,  1, 11],
       [12,  9, 13],
       [ 0, 13,  1],
       [10,  8,  9]])

In [54]:
d1.shape

(5, 3)

In [60]:
dotproduct = np.dot(c, d1)

In [61]:
dotproduct

array([[12.44621785, 18.00194691, 19.14853391],
       [22.96855946, 34.3968055 , 26.39488366],
       [ 9.04394918, 22.12438862, 12.5073394 ]])

In [62]:
dotproduct.size

9

In [64]:
c.shape, d1.shape, dotproduct.shape

((3, 5), (5, 3), (3, 3))

In [94]:
np.random.seed(10)
weekly_buy = np.random.randint(10, size=(5, 3))
weekly_buy


array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

In [95]:
import pandas as pd
buy_count = pd.DataFrame(weekly_buy,
                        index=['sat', 'sun', 'mon', 'tues', 'wed'],
                        columns=['mango', 'Orange', 'egg'])
buy_count

mango  Orange  egg
sat       9       4    0
sun       1       9    0
mon       1       8    9
tues      0       8    6
wed       4       3    0

In [96]:
price = [40, 30, 10]
item_price = pd.DataFrame(price,
                         index=['mango', 'Orange', 'egg'],
                         columns=['price'])
item_price

price
mango      40
Orange     30
egg        10

In [88]:
buy_count.shape, item_price.shape

((5, 4), (3, 1))

In [97]:
total_item_price = np.dot(buy_count, item_price)
total_item_price

array([[480],
       [310],
       [370],
       [300],
       [250]], dtype=int64)

In [98]:
buy_count['weekly Total price $'] = total_item_price
buy_count

mango  Orange  egg  weekly Total price $
sat       9       4    0                   480
sun       1       9    0                   310
mon       1       8    9                   370
tues      0       8    6                   300
wed       4       3    0                   250

In [101]:
total_price = np.sum(buy_count['weekly Total price $'])
total_price

1710

In [104]:
a

array([[ 9, 13,  4,  0,  1],
       [11, 12,  9, 13,  0],
       [13,  1, 10,  8,  9]])

In [105]:
b

array([[ 0, 40, 36, 16, 11, 54, 88, 62, 33, 72],
       [78, 49, 51, 54, 77, 69, 13, 25, 13, 92],
       [86, 30, 30, 89, 12, 65, 31, 57, 36, 27],
       [18, 93, 77, 22, 23, 94, 11, 28, 74, 88],
       [ 9, 15, 18, 80, 71, 88, 11, 17, 46,  7],
       [75, 28, 33, 84, 96, 88, 44,  5,  4, 71],
       [88, 88, 50, 54, 34, 15, 77, 88, 15,  6],
       [85, 22, 11, 12, 92, 96, 62, 57, 79, 42],
       [57, 97, 50, 45, 40, 89, 73, 37,  0, 18],
       [23,  3, 29, 16, 84, 82, 14, 51, 79, 17]])

In [106]:
c

array([[0.453105  , 0.74486408, 0.55729541, 0.3851136 , 0.1680728 ],
       [0.83826132, 0.5990518 , 0.78271482, 0.84850918, 0.60316298],
       [0.78106062, 0.61573688, 0.02116519, 0.75046461, 0.17604213]])

In [107]:
d

array([[ 9, 13,  4,  0,  1],
       [11, 12,  9, 13,  0],
       [13,  1, 10,  8,  9]])

In [108]:
d1

array([[ 9, 13,  4],
       [ 0,  1, 11],
       [12,  9, 13],
       [ 0, 13,  1],
       [10,  8,  9]])

In [113]:
a >= d

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [114]:
a, d

(array([[ 9, 13,  4,  0,  1],
        [11, 12,  9, 13,  0],
        [13,  1, 10,  8,  9]]),
 array([[ 9, 13,  4,  0,  1],
        [11, 12,  9, 13,  0],
        [13,  1, 10,  8,  9]]))

In [118]:
x = a==d

In [119]:
x

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [125]:
a[1:2]

array([[11, 12,  9, 13,  0]])

In [121]:
a

array([[ 9, 13,  4,  0,  1],
       [11, 12,  9, 13,  0],
       [13,  1, 10,  8,  9]])

In [126]:
np.random.seed(10)
random_array = np.random.randint(100, size=(10, 10))
random_array

array([[11, 54, 88, 62, 33, 72, 78, 49, 51, 54],
       [77, 69, 13, 25, 13, 92, 86, 30, 30, 89],
       [12, 65, 31, 57, 36, 27, 18, 93, 77, 22],
       [23, 94, 11, 28, 74, 88,  9, 15, 18, 80],
       [71, 88, 11, 17, 46,  7, 75, 28, 33, 84],
       [96, 88, 44,  5,  4, 71, 88, 88, 50, 54],
       [34, 15, 77, 88, 15,  6, 85, 22, 11, 12],
       [92, 96, 62, 57, 79, 42, 57, 97, 50, 45],
       [40, 89, 73, 37,  0, 18, 23,  3, 29, 16],
       [84, 82, 14, 51, 79, 17, 50, 53, 25, 48]])

In [127]:
sorted_random_array = np.sort(random_array)
sorted_random_array

array([[11, 33, 49, 51, 54, 54, 62, 72, 78, 88],
       [13, 13, 25, 30, 30, 69, 77, 86, 89, 92],
       [12, 18, 22, 27, 31, 36, 57, 65, 77, 93],
       [ 9, 11, 15, 18, 23, 28, 74, 80, 88, 94],
       [ 7, 11, 17, 28, 33, 46, 71, 75, 84, 88],
       [ 4,  5, 44, 50, 54, 71, 88, 88, 88, 96],
       [ 6, 11, 12, 15, 15, 22, 34, 77, 85, 88],
       [42, 45, 50, 57, 57, 62, 79, 92, 96, 97],
       [ 0,  3, 16, 18, 23, 29, 37, 40, 73, 89],
       [14, 17, 25, 48, 50, 51, 53, 79, 82, 84]])

In [128]:
df = pd.DataFrame(sorted_random_array)
df

0   1   2   3   4   5   6   7   8   9
0  11  33  49  51  54  54  62  72  78  88
1  13  13  25  30  30  69  77  86  89  92
2  12  18  22  27  31  36  57  65  77  93
3   9  11  15  18  23  28  74  80  88  94
4   7  11  17  28  33  46  71  75  84  88
5   4   5  44  50  54  71  88  88  88  96
6   6  11  12  15  15  22  34  77  85  88
7  42  45  50  57  57  62  79  92  96  97
8   0   3  16  18  23  29  37  40  73  89
9  14  17  25  48  50  51  53  79  82  84

In [129]:
argumentsort = np.argsort(random_array)    #gives the index of the sorted array

In [130]:
argumentsort

array([[0, 4, 7, 8, 1, 9, 3, 5, 6, 2],
       [2, 4, 3, 7, 8, 1, 0, 6, 9, 5],
       [0, 6, 9, 5, 2, 4, 3, 1, 8, 7],
       [6, 2, 7, 8, 0, 3, 4, 9, 5, 1],
       [5, 2, 3, 7, 8, 4, 0, 6, 9, 1],
       [4, 3, 2, 8, 9, 5, 1, 6, 7, 0],
       [5, 8, 9, 1, 4, 7, 0, 2, 6, 3],
       [5, 9, 8, 3, 6, 2, 4, 0, 1, 7],
       [4, 7, 9, 5, 6, 8, 3, 0, 2, 1],
       [2, 5, 8, 9, 6, 3, 7, 4, 1, 0]], dtype=int64)

In [137]:
maximumindex = np.argmax(random_array, axis=0)  #givies the index of maximum value

In [138]:
maximumindex

array([5, 7, 0, 6, 7, 1, 5, 7, 2, 1], dtype=int64)

In [133]:
minimumIndex = np.argmin(random_array) #gives the index of minimum value of the array

In [134]:
minimumIndex

84

In [135]:
argumentsort.shape, argumentsort.size, len(argumentsort)

((10, 10), 100, 10)

## Practical example - Numpy i action 

<img src="numpy-images/panda.png">

In [140]:
#turn an images into numpy array

from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [141]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [143]:
panda.shape, panda.size

((2330, 3500, 3), 24465000)